### ISSUE TITLE
Does this plugin support persistence metadata provided via XML instead of annotations?

### ISSUE THREAD

**Issue by chrisco484** [rm3l/datanucleus-gradle-plugin#10]
Not really an issue but I didn't know where else to ask a question :)

We've been using DataNucleus for many years (JDO) via maven and we love it - just looking to change our build tool from maven to gradle so this new gradle plugin for DataNucleus looks very interesting! Thanks for creating it.

**Comment by rm3l** [comment]
Hi there!
Under the hood, all the Gradle tasks added via this plugin leverage the programmatic APIs provided by DataNucleus, for enhancement and schema tool operations. So yes, this plugin does support persistence metadata provided either via XML (with JDO XSD or ORM XSD specifications) or via annotations.
By the way, there is a very simple '[sample-jdo](https://github.com/rm3l/datanucleus-gradle-plugin/tree/master/sample-jdo)' sample project in this repo, which can be used as a starting point for testing this plugin against JDO.
JDO is not fully tested, so please let me know if you run into any issues.
