### ISSUE TITLE
Doc intro about enhancement misleading

### ISSUE THREAD

**Issue by andyjefferson** [rm3l/datanucleus-gradle-plugin#11]
You state 

> Some providers such as DataNucleus have chosen to require all domain classes to be enhanced before any use. This means that enhancement has to be done beforehand at build time, or at any time between compile time and packaging time.

and

> On the other hand, other JPA providers do not make enhancement a mandatory prerequisite, and can do it on-the-fly at run-time.

DataNucleus allows code to be enhanced AT RUNTIME in the exact same way as these other JPA providers you refer to, using a java ClassFileTransformer. Whether it would be recommended to enhance at runtime (for ANY JPA provider) is a totally different question. Perhaps you can correct this misleading description. Thx

**Comment by rm3l** [comment]
Thanks for the feedback, @andyjefferson ! You're right - this is misleading indeed. I'll fix that description..
